apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
  namespace: cookbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: cookbook
  labels:
    app: app1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      version: v1
  template:
    metadata:
      labels:
        app: app1
        version: v1
    spec:
      serviceAccountName: app1
      containers:
      - name: app1
        image: curlimages/curl
        command:
        - /bin/sleep
        - infinity
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app1
  namespace: cookbook
spec:
  workloadSelector:
    labels:
      app: app1
  egress:
  - hosts:
    - istio-system/*
    - ./*
    - cookbook-app1-egress/*
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
---