apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin
  namespace: cookbook-app2-egress
spec:
  hosts:
  - httpbin.org
  ports:
  - name: http
    protocol: HTTP
    number: 80
  - name: tls
    protocol: TLS
    number: 443
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin
  namespace: cookbook-app2-egress
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - httpbin.org
    port:
      name: http
      protocol: HTTP
      number: 80
  - hosts:
    - httpbin.org
    port:
      name: tls
      protocol: TLS
      number: 443
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: cookbook-app2-egress
spec:
  hosts:
  - httpbin.org
  gateways:
  - mesh
  - httpbin
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 80
  - match:
    - gateways:
      - httpbin
      port: 80
    route:
    - destination:
        host: httpbin.org
        subset: tls-origination
        port:
          number: 443
  tls:
  - match:
    - gateways:
      - mesh
      sni_hosts:
      - httpbin.org
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
  - match:
    - gateways:
      - httpbin
      sni_hosts:
      - httpbin.org
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin
  namespace: cookbook-app2-egress
spec:
  host: httpbin.org
  subsets:
  - name: tls-origination
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
---