apiVersion: v1
kind: ServiceAccount
metadata:
  name: app2
  namespace: cookbook
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: cookbook
  labels:
    app: app2
    version: v1
spec:
  selector:
    app: app2
    version: v1
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: cookbook
  labels:
    app: app2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      version: v1
  template:
    metadata:
      labels:
        app: app2
        version: v1
    spec:
      serviceAccountName: app2
      containers:
      - name: app2
        image: curlimages/curl
        command:
        - /bin/sleep
        - infinity
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app2
  namespace: cookbook
spec:
  workloadSelector:
    labels:
      app: app2
  egress:
  - hosts:
    - istio-system/*
    - ./*
    - cookbook-app2-egress/*
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
---